version: "3.9"

services:

  dashboard:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: >
      sh -c "python3 responder.py & python3 dashboard.py"
    volumes:
      - ./app/templates:/app/templates
    ports:
      - "5000:5000"
    networks:
      - mqtt-net
    restart: no

networks:
  mqtt-net:
    driver: bridge


